### ISSUE TITLE
Утечка памяти после выполнения запросов на сервер

### ISSUE THREAD

**Issue by rareMaxim** [ms301/CloudAPI#1]
Максим, здравствуйте!
Хочется сказать спасибо, за библиотеку TelegramBot для Delphi. 
Классная вещь! А вы отмечали что происходит утечка памяти если зациклить методы getUpdates или getMe? Все что подхватывает TelegramBot.API
(с) Roman Chaplyankov

**Comment by ms301** [comment]
Исправлено

**Comment by rareMaxim** [comment]
Исправлено
