### ISSUE TITLE
Документ возвращает 404

### ISSUE THREAD

**Issue by Dev-Demi** [ms301/CloudAPI#100]
### TelegaPi version/Версия TelegaPi
> v.3.5.5
### IDE version/ Версия IDE
> RAD Studio Berlin
### Information/Информация
 В обработчике события procedure 
`TForm1.tgReceiverUI1Message(ASender: TObject; AMessage: ITgMessage);`
пытаюсь получить ссылку на файл
```
if AMessage.&Type =TtgMessageType.Document  then
 begin
  memo1.Lines.Add(AMessage.Document.GetFileUrl(TelegramBot1.Token))
 end;
```
Приходит ответ - 404
### Steps to reproduce the behavior/Что нужно сделать, для воспроизведения
Воспроизводится всегда

**Comment by rareMaxim** [comment]
s := TelegramBot1.GetFile(AMessage.Document.FileId).GetFileUrl(TelegramBot1.Token)

**Comment by Dev-Demi** [comment]
Да, так норм, спасибо!
