### ISSUE TITLE
Не работает внутри DLL

### ISSUE THREAD

**Issue by TimKruz** [ms301/CloudAPI#11]
Пытаюсь использовать внутри DLL, ошибок никаких не выдаёт, но процедура, в которой должны обрабатываться получаемые ботом сообщения, просто не вызывается. Демки работают корректно.

**Comment by rareMaxim** [comment]
Попробуй собрать библиотеку из ветки [hotfix/recesive_upd_id_dll ](https://github.com/ms301/TelegAPI/tree/hotfix/recesive_upd_id_dll).
Далее открываешь _свойства dll -- Delphi compiler_. _Target_ ставишь в **All configuration - All platforms**. 
В поле _Conditional defines_ пишешь **NO_QUEUE**
Проверь - будет ли нормально работать. О результатах сообщи, что бы я мог исправление в мастер-ветку закинуть если все работает, либо еще что-либо исправить.

**Comment by TimKruz** [comment]
Всё сделал. Теперь он вызывает процедуру обработки сообщений только перед вызовом мною `Telegram.Free`. Т.е. я создаю объект, пишу боту в чате, бот не реагирует, я освобождаю объект, а он начинает обрабатывать сообщения. При этом обрабатывает не всегда и не все: иногда не обрабатывает ничего, иногда - только 2-3 первых или 2-3 последних сообщения, а иногда обрабатывает одно и то же сообщение несколько раз - поставил отправку сообщений обратно и отправил пять разных сообщений - вернулось последнее сообщение пять раз. Такие дела.

**Comment by TimKruz** [comment]
Всё, теперь всё работает, спасибо!
