### ISSUE TITLE
x64 support?

### ISSUE THREAD

**Issue by mad1979** [ms301/CloudAPI#14]
Yes or No?

**Comment by rareMaxim** [comment]
Telega π does not contain platform-independent code. You can run this library on any platform that RAD Studio supports

**Comment by turric4n** [comment]
indeed




Obtener Outlook para Android







On Fri, Jun 2, 2017 at 7:56 AM +0200, "Maxim Sysoev" <notifications@github.com> wrote:












Telega π does not contain platform-independent code. You can run this library on any platform that RAD Studio supports

**Comment by mad1979** [comment]
I can't add component on form in 64-bit windows vcl application

P.S. delphi xe10

**Comment by rareMaxim** [comment]
@mad1979 on 32-bit - you can add component?

**Comment by mad1979** [comment]
Yes, I can

**Comment by mad1979** [comment]
Only Win32 platform is enabled in TelegaPiBot.dproj

**Comment by rareMaxim** [comment]
Add the required platforms, and reinstall the component
