### ISSUE TITLE
Ошибка "brcc32 exited with code 9009" при сборке bpl.

### ISSUE THREAD

**Issue by ghost** [ms301/CloudAPI#19]
На компьютерах, где по какой-то причине каталог Bin от Delphi не попал в переменную Path, при попытке собрать пакет появляется ошибка "brcc32 exited with code 9009", после чего сборка завершается. Причина в командах "до сборки", где brcc32 вызывается без пути к файлу. Чтобы проект успешно собирался, предлагаю заменить команду на полный прототип:

"$(BDS)\Bin\brcc32.exe" -fo "$(PROJECTDIR)\TTelegramBot.dcr" "$(PROJECTDIR)\TTelegramBot.rc"

**Comment by rareMaxim** [comment]
не могу повторить у себя эту проблему. Если у кого-то повторяется - сообщите, будем вместе разбираться
