### ISSUE TITLE
Where's token.inc

### ISSUE THREAD

**Issue by margond** [ms301/CloudAPI#25]
The Demo program uses the token.inc that wasn't in the project. Can you attach the file please?
Thanks in advance

**Comment by rareMaxim** [comment]
open demo project. find method **procedure TMain.FormCreate(Sender: TObject);**
replace 
**tgBot.Token := {$I ..\token.inc};**
to 
**tgBot.Token := 'token from [botfather](http://t.me/BotFather)';**

**Comment by margond** [comment]
I get the raised error "invalid token format" when execute, in the FormCreate.
My code is:

  ReportMemoryLeaksOnShutdown := True;
  tgBot.Token := 'token from botfather';     
  if not tgBot.IsValidToken then
    raise ELoginCredentialError.Create('invalid token format');
  tgBot.IsReceiving := True;

Whats wrong?

**Comment by rareMaxim** [comment]
Really? please, read https://core.telegram.org/bots#3-how-do-i-create-a-bot. you need create bot via http://t.me/BotFather, get token and paste to tgBot.Token

**Comment by margond** [comment]
Jejeje. Sorry. My mind its a bit slowly today. I understand you now. Thanks
