### ISSUE TITLE
Функции с инлайн-клавиатурой в параметрах содержит маркап-клавиатуру.

### ISSUE THREAD

**Issue by ghost** [ms301/CloudAPI#28]
EditMessageReplyMarkup, SendPhoto и другие функции имеют тип параметра "ReplyMarkup: TtgReplyKeyboardMarkup", тогда как по логике должны быть TtgInlineKeyboardMarkup. Простая замена типа параметра - и функция начинает работать правильно, выводя клавиатуру.

Неплохо было бы вообще привести тип к интерфейсному IReplyMarkup, но нужно быть осторожным, во избежание ошибок "Invalid pointer operation".

**Comment by rareMaxim** [comment]
@deadalice В качестве параметра будет интерфейс. некоторые методы перевел - про остальные забыл. Постараюсь остальные перевести завтра
