### ISSUE TITLE
InlineMessageId пуст при вызове колбэка.

### ISSUE THREAD

**Issue by ghost** [ms301/CloudAPI#29]
В CallbackQuery запись ACallbackQuery.InlineMessageId пуста, хотя должна содержать уникальный идентификатор сообщения.

**Comment by rareMaxim** [comment]
https://tlgrm.ru/docs/bots/api#callbackquery

> Если кнопка была показана в сообщении, отправленном при помощи [встроенного режима,](https://tlgrm.ru/docs/bots/api#inline-mode) в запросе будет присутствовать поле **inline_message_id**.
