### ISSUE TITLE
Cant install/compile  XE7

### ISSUE THREAD

**Issue by 0x92** [ms301/CloudAPI#3]
When i try to compile/install the install dpk i get the following error

[dcc32 Fataler Fehler] TelegAPI.Bot.pas(11): F1026 Datei nicht gefunden: 'C:\delphilib\Telegram\TelegAPI-master\Install\System.Net.Mime.dcu'
![bds_2016-12-13_11-02-32](https://cloud.githubusercontent.com/assets/6593435/21135989/0bf3c522-c124-11e6-904e-9866de5c85e9.png)

**Comment by rareMaxim** [comment]
I'm sorry, but is currently supported version of Delphi is XE8 - Berlin.

**Comment by 0x92** [comment]
:((( Is there no chance to make it compatible with older versions? would like to contribute but got xe7

**Comment by rareMaxim** [comment]
I will try to add support XE7.

**Comment by rareMaxim** [comment]
Please, check branch [XE7](https://github.com/ms301/TelegAPI/tree/feature/XE7)
