### ISSUE TITLE
vpn network

### ISSUE THREAD

**Issue by megatkurniawan** [ms301/CloudAPI#39]
helo, i have problem if my network on vpn. 
error message like this:
**error Execution of request terminated with unknown error**

but if my network not in vpn telegAPI goes well.

how to resolve error?

**Comment by ghost** [comment]
Check if https://core.telegram.org/ is available under VPN from any browser.

**Comment by andb24** [comment]
Hello megatkurniawan.
How frequently did you make those requests? 
Maybe NAT internal cache time expired in the router. 
Try to keep constant ping to core.telegram.org launched during your requests. 
ping -t core.telegram.org

**Comment by megatkurniawan** [comment]
helo andb24 when a successful bot connection, but when there is a new message then the connection immediately disconnected and error messages as above will appear. and I've been pinging continuously to core.telegram.org but still the problem

**Comment by megatkurniawan** [comment]
sorry deadalice, I did not find any explanation about vpn on https://core.telegram.org/

**Comment by andb24** [comment]
megatkurniawan, I recalled right address of API server:
api.telegram.org
This address is for request receiving. Try ping it.  Every ping resets the timeout of holding info about remote server in the router's nat table,

**Comment by rareMaxim** [comment]
You can use _TTelegramBot.ProxySettings_
