### ISSUE TITLE
TelegaPi.Types not found.

### ISSUE THREAD

**Issue by turric4n** [ms301/CloudAPI#4]
Hi,

TelegaPi.Types.pas isn't included in the GIT repo.

**Comment by rareMaxim** [comment]
Hello.
TelegaPi.Types is now TelegAPi.Classes

Show a file refers to TelegaPi.Types ?

**Comment by turric4n** [comment]
Hi, 

Thanks for your quick response. 

Here is the list with the old unit reference :

Filename
--------
README.md
README.md
TelegramServer.dpr
uMain.pas

**Comment by rareMaxim** [comment]
see demo https://github.com/ms301/TelegAPI/tree/master/Demo/AutoRecesiveMsg
