### ISSUE TITLE
В деструкторе TTgMessage отсутствует free для SuccessfulPayment?

### ISSUE THREAD

**Issue by andb24** [ms301/CloudAPI#41]
class: 
...
[Alias('successful_payment')]
    SuccessfulPayment: TtgSuccessfulPayment;
end;
.....
destructor TtgMessage.Destroy;
begin
  FreeAndNil(From);
  FreeAndNil(Chat);
  FreeAndNil(ForwardFrom);
  FreeAndNil(ForwardFromChat);
  FreeAndNil(ReplyToMessage);
  FreeAndNil(Audio);
  FreeAndNil(Document);
  FreeAndNil(Sticker);
  FreeAndNil(Video);
  FreeAndNil(Voice);
  FreeAndNil(Contact);
  FreeAndNil(Location);
  FreeAndNil(Venue);
  FreeAndNil(LeftChatMember);
  FreeAndNil(PinnedMessage);
  FreeAndNil(ForwardFromChat);
  FreeAndNil(NewChatMember);
  FreeAndNil(NewChatMembers);
  FreeAndNil(Photo);
  FreeAndNil(Entities);
  FreeAndNil(NewChatPhoto);
  FreeAndNil(Game);
  inherited Destroy;
end;

**Comment by rareMaxim** [comment]
Fixed in df443fd
