### ISSUE TITLE
problem with json package

### ISSUE THREAD

**Issue by Abbas-509** [ms301/CloudAPI#45]
unfortunately, There is some issue on JsonDataObjects.TJsonDataValue class, and we can not to use  this package

**Comment by rareMaxim** [comment]
Show me screnshoot IDE with issue

**Comment by Abbas-509** [comment]
[Test3.zip](https://github.com/ms301/TelegAPI/files/1360628/Test3.zip)
![error](https://user-images.githubusercontent.com/5670951/31248756-c00f5030-aa21-11e7-8f78-524a12a4f140.jpg)

**Comment by rareMaxim** [comment]
Version Bot version 3.3.1? And tell me - what text should I send to the bot, what would be the error?

**Comment by Abbas-509** [comment]
i'm using 3.3.1 (last version) and also last DJSON release, 
error is just when i'm using this <Code>TgBotAsync1.IsReceiving := true; </code>
(you can see my simple attached source code at last post )

**Comment by rareMaxim** [comment]
@Abbas-509 please, use Develop branch of DJSON, or included version of DJSON(ms301-TelegAPI\modules\DJSON\Sources)

**Comment by Abbas-509** [comment]
Thanks, you've solved my problem. 🙂
