### ISSUE TITLE
Чат ID определяется неверно

### ISSUE THREAD

**Issue by mvgx** [ms301/CloudAPI#49]
Chat ID при компиляции бота под win32 или win64 определяется неверно, как 32-битный integer вместо int64.
Ошибка в функции 
```
TdjEngineJDO.DeserializeInt(const AJSONValue: PJsonDataValue;  const AValueType: TRttiType): TValue;
begin
  if not Assigned(AJSONValue) or (AJSONValue.Typ = TJsonDataType.jdtNone)  then
    Result := 0
  else
_// нужно так:_
    **If AValueType.TypeKind=tkInt64 then Result := AJSONValue.LongValue** else Result := AJSONValue.IntValue;
end;

```
Кроме того, при компиляции под win64 ошибка в TdjEngineJDO.DeserializeArray. Нужно задавать   LArrayLen: nativeint; вместо   LArrayLen: Longint;

**Comment by rareMaxim** [comment]
https://github.com/ms301/DJSON/tree/develop - проверь, пожалуйста, эту версию и сообщи - все ли нормально? У меня, нет под рукой сейчас x64 ОСи.

**Comment by mvgx** [comment]
Да, с этой версией все нормально! Спасибо!

**Comment by rareMaxim** [comment]
@mauriziodm - check your repository :)
