### ISSUE TITLE
Lazarus

### ISSUE THREAD

**Issue by Al-Muhandis** [ms301/CloudAPI#51]
Нет ли у Вас мыслей портировать для Lazarus?

**Comment by rareMaxim** [comment]
Возможно в будущем. Сейчас нет желания. 

Мне нравится Lazarus - но, к сожалению, там нет ни анонимных методов, ни дженериков, ни RTTI. По этой причине портировать на него тяжело(но возможно).

**Comment by Al-Muhandis** [comment]
Понятно. Спасибо. Кстати, насчет анонимных методов не знаю, но дженерики и RTTI в Lazarus есть...

**Comment by rareMaxim** [comment]
@Al-Muhandis, работа с https там через Indy?

**Comment by TimKruz** [comment]
@ms301 Установить Indy10 можно, но, похоже, работает пока немного костыльно:
http://wiki.lazarus.freepascal.org/Indy_with_Lazarus
http://www.freepascal.ru/article/lazarus/20100812185950

**Comment by Al-Muhandis** [comment]
@ms301 лично я привык работать с [synapse](http://synapse.ararat.cz/) и в нем есть поддержка https. Но поддержка Indy также имеется

**Comment by Al-Muhandis** [comment]
@TimKruz разработчики в Lazarus indy пользуются (насчет версии не в курсе), но по работе Indy в Lazarus, к сожалению, не могу подсказать.

**Comment by rareMaxim** [comment]
@Al-Muhandis - не уверен что получится, но проведу исследования для проверки, получится ли добавить совместимость с Lazarus.

**Comment by Al-Muhandis** [comment]
Спасибо. Я, кстати, пока приспособил один заброшенный проект TGBotLazarus, начатый не мной - веду пока его. Думал сначала перевести в Lazarus Вашу библиотеку, но понял что не хватит знаний и времени. А сделать первые боты уже давно хотел. Еще раз, спасибо, за намерение помочь разработчикам в Lazarus.

**Comment by rareMaxim** [comment]
К сожалению, Lazarus не имеет библиотек для (де)сериализации объектов. Поэтому поддержка этой ИДЕ не планируется в ближайщее время.
