### ISSUE TITLE
required DJSON_Project not found

### ISSUE THREAD

**Issue by Quecksgold** [ms301/CloudAPI#53]
I downloaded TelegAPI and tried to complile it by hitting F9, but Delphi told me that the DJSON_Project package could not be found. Google didn't help me, so I wanted to ask, where do I get this DJSON_Project from?

**Comment by GoLover** [comment]
Use this repository https://github.com/ms301/DJSON
@Quecksgold

**Comment by Quecksgold** [comment]
thanks for the quick response :)

**Comment by GoLover** [comment]
@Quecksgold your welcome please close the issue using button below here

**Comment by Quecksgold** [comment]
I've tried TelegAPI and I am excited so far. Good job.
But there is one thing I still dont get: When I choose "EchoBot.exe" and compile it, it runs without problems, also editing the source code to send/receive different stuff it works fine, but when I try to edit the GUI (by clicking on the EchoBot.Main.fmx inside the projectmanager) then it throws an error like this:
Class TTelegramBot not found. Ignore the Error and continue? WARNING: Ignoring the error may result in components or propertys getting lost/deleted. [ignore] [abort] [ignore all]

So how do I edit the fmx GUI for the EchoBot?
