### ISSUE TITLE
Failed editing GUI in EchoBot.Main.fmx

### ISSUE THREAD

**Issue by Quecksgold** [ms301/CloudAPI#54]
I've tried TelegAPI and I am excited so far. Good job.
But there is one thing I still dont get: When I choose "EchoBot.exe" and compile it, it runs without problems, also editing the source code to send/receive different stuff works fine, but when I try to edit the GUI (by clicking on the EchoBot.Main.fmx inside the projectmanager) then it throws an error like this:
Class TTelegramBot not found. Ignore the Error and continue? WARNING: Ignoring the error may result in components or propertys getting lost/deleted. [ignore] [abort] [ignore all]

If I click on [ignore] it comes up with another error, saying the class "TTgBotRecesiverUI" is missing too - so same error with another class.
If I ignore the warnings I can edit the fmx GUI controls, but then some (many) things in the source code won't work of course and if I abort the error(s), then I can't edit the GUI.

So my question is: 
Where do I get these missing classes class from? Or how can I otherwise edit the GUI by ensuring the code will still work?

**Comment by andb24** [comment]
Hello. 
Have you installed DJSON (before telegAPI) and telegAPI components into your delphi?
DJSON components should be **from the ms301** fork.

**Comment by Quecksgold** [comment]
No, thanks for this question. I installed it and now it works :)

2017-11-08 5:45 GMT+01:00 andb24 <notifications@github.com>:
