### ISSUE TITLE
Пример не работает

### ISSUE THREAD

**Issue by seoeaa** [ms301/CloudAPI#59]
/help
SendDataToServer@Access violation at address 0045C6DC in module 'EchoBot.exe'. Read of address FFFFFFB9
RequestAPI@Can't parse response

**Comment by seoeaa** [comment]
tgBot.SendMessage(Msg.Chat.Id, usage, TtgParseMode.default, False, False, 0, TtgReplyKeyboardRemove.Create);

**Comment by rareMaxim** [comment]
@aleksandrguru что находится в usage в момент отправки сообщения?

**Comment by seoeaa** [comment]
Просто команду /help отправляю и все 

  else if Msg.IsCommand('/help') then // send
  begin
    usage := 'Usage:' + #13#10 + //
      '/inline   - send inline keyboard' + #13#10 + //
      '/keyboard - send custom keyboard' + #13#10 + //
      '/photo    - send a photo' + #13#10 + //
      '/request  - request location or contact';
    tgBot.SendMessage(Msg.Chat.Id, usage, TtgParseMode.default, False, False, 0, TtgReplyKeyboardRemove.Create);
  end;

**Comment by seoeaa** [comment]
Стандартный пример ничего не менял только токен

**Comment by seoeaa** [comment]
/inline
SendDataToServer@Access violation at address 0045C6DC in module 'EchoBot.exe'. Read of address FFFFFFB9
RequestAPI@Can't parse response

**Comment by seoeaa** [comment]
Остальные все команды работают

**Comment by seoeaa** [comment]
/help 

тут ошибка 

TtgReplyKeyboardRemove.Create

**Comment by rareMaxim** [comment]
@aleksandrguru - проверь ветку develop - там уже будет рабочая версия. Но должен понимать что это еще не полностью протестированный код.

**Comment by seoeaa** [comment]
Спасибо протестирую , а то самое интересно не работает)) Еще вопрос как определить тип сообщения , что то у меня не выходит контакт пользователя получить который он отправляет.

**Comment by rareMaxim** [comment]
@aleksandrguru В последнем комите в develop ветке добавил метод в котором идет получение инфы о контакте
