### ISSUE TITLE
Way to detect if someone joins a group?

### ISSUE THREAD

**Issue by AdriaanBoshoff** [ms301/CloudAPI#61]
Not an issue
### Expected behavior
Sends a message as soon as someone joins a group where the bot is in.

### Actual behavior
Does nothing.

### Steps to reproduce the behavior
I'm not sure how I can do this. Any ideas?

**Comment by rareMaxim** [comment]
@AdriaanBoshoff In event *OnMessage* check methods ITgMessage.NewChatMember and ITgMessage.NewChatMembers

**Comment by AdriaanBoshoff** [comment]
Thanks will check it out.

**Comment by AdriaanBoshoff** [comment]
Is it possible to give an example? I'm lost on this, So far I have the case statement that was in the echo bot but I'm unsure on how to add ITgMessage.NewChatMember and ITgMessage.NewChatMembers since they don't seem to be able to be used there.

**Comment by rareMaxim** [comment]
in component _TtgReceiver_ open event _OnMessage_ and add cod:
```
if AMessage.NewChatMember <> nil then
    WriteLine('NEW CHAT MEMBER: ' + AMessage.NewChatMember.FirstName + ' ' + AMessage.NewChatMember.LastName);
```

**Comment by AdriaanBoshoff** [comment]
Thanks!
