### ISSUE TITLE
Не работает метод SendVideo

### ISSUE THREAD

**Issue by 9223000** [ms301/CloudAPI#62]
Вызываю метод, аналогично SendFoto в примерах: tgBot.SendVideo(theChatID,TtgFileToSend.FromFile('c:\testmp4\test.mp4'));
Получаю:  OnGlobalException: RequestAPI@Could not convert variant of type (UnicodeString) into type (Double)

**Comment by rareMaxim** [comment]
Тестовый фикс в [develop](https://github.com/ms301/TelegaPi/tree/develop) ветке.
