### ISSUE TITLE
Метод SendMessage не отправляет сообщение в публичный канал

### ISSUE THREAD

**Issue by 9223000** [ms301/CloudAPI#63]
Есть публичный канал, мой бот (TelegaPi) добавлен как администратор канала и имеет все привилегии, бот пытается послать сообщение в канал, но получает:
 OnApiException: TTelegramBot.ApiTest@EApiRequestException:
   ErrorCode = 0. Message = {"ok":false,"error_code":400,"description":"Bad Request: chat not found"}

Хотя, скажем на версии Bot API: *3.3.0* отправка сообщения в публичный канал работала.

Метод вызывался так:
tgBot.SendMessage('-999999','Test Message');
где -999999 - это ID публичного канала

**Comment by rareMaxim** [comment]
Метод SendMessage отправляет сообщения в публичный канал(проверено на версии 6289ccb338). При этом работает отправка как по ИД, так и по имени чата:

>   tgBot.SendMessage(-1001348684203, 'Direct ID');
  tgBot.SendMessage('@MyTestChanelDelphi', 'ChatName');

Проверьте ИД Вашего канала
