### ISSUE TITLE
Выполнение методов tgBot в отдельном потоке

### ISSUE THREAD

**Issue by 9223000** [ms301/CloudAPI#65]
Было бы неплохо указывать методу tgBot выполнения его в отдельном потоке, так например при вызове метода SendVideo где файл достаточно большой (10 Мб) основное приложение во время исполнения метода, как бы "замирает" оно и понятно, т.к. метод tgBot выполняется в основном потоке приложения, а было бы неплохо при вызове метода явно указать выполнять его в отдельном потоке или нет.

**Comment by TimKruz** [comment]
ИМХО, если у тебя бот является частью какого-то большого приложения, а не самостоятельной программой, то имеет смысл вынести в отдельный поток весь экземпляр TTelegramBot, чтобы интерфейс и основная логика приложения не зависели от состояния той части, которая общается с серверами Телеграма.

А то ты можешь ожидать, что сообщение из 100 символов отправится за миллисекунды (исходя из малого объёма передаваемых данных), и приказать методу отправки выполняться в основном потоке, а на практике произойдёт какая-нибудь скрытая ошибка при передаче или задержка в сети, и у тебя подвесится всё приложение, а ты потом будешь ломать голову, почему возник этот глюк и как его предотвратить в будущем. 😀

**Comment by 9223000** [comment]
Главное понимать свои алгоритмы и уметь их контролировать, так я уже попробовал использовать методы TgBot в параллельных потоках с использованием класса TTask, все успешно, отлично работает, производительность и отклик бота повысилось. Но, еще раз, нужно контролировать все алгоритмы, чтобы исключить не предвиденных Exceptions....
