### ISSUE TITLE
Error in sending sendMediaGroup 

### ISSUE THREAD

**Issue by ghost** [ms301/CloudAPI#66]
Hi,
When calling sendMediaGroup I will get the below error message 
**_"Internal: Type tkPointer is not currently support"_**
Here is my code.

```
var
  AMedia: System.TArray<TelegAPI.Types.TtgInputMedia>;
  Media: TtgInputMedia;
  Media2: TtgInputMedia;

begin
  SetLength(AMedia,2);
  Media := TtgInputMedia.Create('c:\temp\1.jpg');
  AMedia[0] := Media;
  Media2 := TtgInputMedia.Create('c:\temp\2.jpg');
  AMedia[1] := Media2;
  TelegramBot1.sendMediaGroup( 111111111,,AMedia);

end;
```
Please bring an example to call the procedure

**Comment by rareMaxim** [comment]
Sorry, but now method sendMediaGroup not supported

**Comment by rareMaxim** [comment]
Method sendMediaGroup now work started from v3.5.3
