### ISSUE TITLE
Не работает proxy

### ISSUE THREAD

**Issue by Xvir43** [ms301/CloudAPI#71]
не работает 
tgBot.ProxySettings:=TProxySettings.Create('111.11.111.11', 443, 'login','pass');
дает ошибку :
RequesRequestAPI@Server Certificate Invalid or not present

**Comment by rareMaxim** [comment]
Вот так указываю прокси - и бот работает:
```
  LBot := TTelegramBot.Create('283107814:AAGOGxUCwTC2g');
{}  (LBot as TTelegramBot).ProxySettings := TProxySettings.Create('193.151.106.199', 8080);
  LReceiver := TtgReceiverConsole.Create(LBot);
```
Попробуйте проверить работу у другого оператора, судя по ошибке - ваш провайдер(либо вредоностное ПО) пытается подменить сертификат.

**Comment by Xvir43** [comment]
Опытным путем (поставив виртуальную машину) выяснилось что дело в провайдере, спасибо.
