### ISSUE TITLE
Загрузка поля Description взята с метода для поля Text ?

### ISSUE THREAD

**Issue by andb24** [ms301/CloudAPI#74]
https://github.com/ms301/TelegaPi/blob/4ac2cb3d04fccb22979cad44c29c96b2552047d7/Source/TelegAPi.Types.Impl.pas#L1560

ошибка "COPY-PASTE"?
![image](https://user-images.githubusercontent.com/31127262/39953339-9478b4fe-55dc-11e8-851c-97bcd4f25836.png)

**Comment by rareMaxim** [comment]
Fix in d551a23
