### ISSUE TITLE
Загрузка поля Animation.data вместо "file_id String Unique file identifier"

### ISSUE THREAD

**Issue by andb24** [ms301/CloudAPI#75]
https://github.com/ms301/TelegaPi/blob/4ac2cb3d04fccb22979cad44c29c96b2552047d7/Source/TelegAPi.Types.Impl.pas#L408

Верное ли загружается поле?
![image](https://user-images.githubusercontent.com/31127262/39953406-ecf9ee1c-55dd-11e8-9b77-a5334b555b58.png)

**Comment by rareMaxim** [comment]
Fix in a3e5fd7
