### ISSUE TITLE
Подозрение на лишний inherited для abstract-методов

### ISSUE THREAD

**Issue by andb24** [ms301/CloudAPI#76]
https://github.com/ms301/TelegaPi/blob/9444b76e45af14d5d1997d781429a8e5f50443da/Source/TelegAPI.Receiver.Console.pas#L62

Из анализа наследования получается, что вызывать inherited для **некоторых** событий лишнее.
Там нет реализации для методов. 

см. дерево классов:
тут объявлены абстрактные обработчики событий
 TTgBotUpdateParser = class(TtgAbstractComponent)
![image](https://user-images.githubusercontent.com/31127262/40105346-43655378-5925-11e8-8180-785defc6a18d.png)

тут их перекрытий нету, т.е. абстракты идут дальше
 TTgBotReceiverBase = class(TTgBotUpdateParser, ITgBotReceiverBase)
![image](https://user-images.githubusercontent.com/31127262/40105366-5021630e-5925-11e8-9b5e-cfff5d18a10c.png)

здесь описаны override-методы
TtgReceiverConsole = class(TTgBotReceiverBase)
![image](https://user-images.githubusercontent.com/31127262/40105388-5f08d096-5925-11e8-8d75-dbda7f7005d3.png)

**Comment by andb24** [comment]
это некоторые из них:
![image](https://user-images.githubusercontent.com/31127262/40105532-cd610a90-5925-11e8-9c69-faf25ef04041.png)

**Comment by andb24** [comment]
Абстрактные методы это реально пустышки, обозначения для компилятора, что есть такие названия методов.  Их можно пропускать в override-методах.

Раньше в дельфе, до директивы **abstract**, делалось примерно так:
```
procedure TStream.Write(...);
begin
  raise exception ('abstact method!');
end;
```

**Comment by kami-soft** [comment]
Не вижу в inherited в данном случае ничего плохого.

Компилятор не генерирует код для inherited, если он ведет в метод абстрактного класса, т.е. Abstract Error не возникнет.
А вот в случае, если базовый класс вдруг обзаведется логикой в этом методе -  inherited придется добавлять.

**Comment by andb24** [comment]
Так вот лучше бы эти inherited в конструкторах оставить. Там в некоторых нету этих вызовов.
А так создаётся видимость имхо, некого базового функционала в классе-предке.
Технически же классы работают исправо.
