### ISSUE TITLE
Не работает метод ItgMessage.NewChatMembers

### ISSUE THREAD

**Issue by rareMaxim** [ms301/CloudAPI#77]
При обращении к методу ItgMessage.NewChatMembers появляется ошибка:

> Exception class EJSONException with message 'Conversion from TJSONArray to string is not supported'. Process WelcomeBotVcl.exe (10632)

**Comment by isaidanielramirez13** [comment]
<bedd6199d0d33b52a5387380f9350b30> /usr/lib/libobjc.A.dylib
0x1826e0000 - 0x1826e5fff libcache.dylib arm64
