### ISSUE TITLE
How to get "CrossUrl" when I compiling "InstallAndDemo.groupproj".

### ISSUE THREAD

**Issue by yuchanz** [ms301/CloudAPI#82]
Hello, I want to make a telegram bot. and I found this TelegaPi. However, I get an error that likes "not found the package CrossUrl" when I compiling InstallAndDemo.groupproj.  Where can I get "CrossUrl"?
Thank you

**Comment by rareMaxim** [comment]
@yuchanz Install this lib: https://github.com/ms301/CrossUrl
