### ISSUE TITLE
parameter DisableNotification not work

### ISSUE THREAD

**Issue by atimofeev86** [ms301/CloudAPI#88]
### TelegaPi version/Версия TelegaPi
> v.3.5.5
### IDE version/ Версия IDE
> RAD Studio Berlin
### Information/Информация
> The SendMessage method ignore parameter 'DisableNotification', when I set TRUE the message send with notification.
### Steps to reproduce the behavior/Что нужно сделать, для воспроизведения
> I call the method, similarly to SendMessage  with parameter DisableNotification = true

**Comment by rareMaxim** [comment]
Try update Telegram library to CloudAPI. 
How setup/update: 
Update project from git: _https://github.com/ms301/TelegaPi_
add _cloudapi\Source\CoreAPI in Library Path_
Install package _\cloudapi\Install\CloudApiCore.dpk_
add _cloudapi\Source\Telegram.org_ в Library Path
Install package _\cloudapi\Install\TelegaPi.dpk_

**Comment by atimofeev86** [comment]
it's work. Thank you!
