### ISSUE TITLE
Не нашел фаил

### ISSUE THREAD

**Issue by seoeaa** [ms301/CloudAPI#9]
TelegAPI.Types

**Comment by rareMaxim** [comment]
А кто на него ссылается?

**Comment by seoeaa** [comment]
uses uVictorine,
  LoggerPro, TelegAPI.Bot, TelegAPI.Types,

Викторина , зачем там не понятно так как не хватает половина файлов

**Comment by seoeaa** [comment]
Можете выложить пример викторины со всеми файлами, а то мало примера Hello Word

**Comment by rareMaxim** [comment]
Викторину удалю, она разрабатывалась для старой версии. Постараюсь в ближайшее время больше примеров написать.
