### ISSUE TITLE
bad Request

### ISSUE THREAD

**Issue by paulolezak** [ms301/CloudAPI#91]
error found in Telegram - Unofficial Demo 

TelegramBot OnError, Exception: [ 18/06/2019 21:02:13 ] (400) Bad Request
TelegramBot OnError ------------------
TelegramBot OnError, Exception: [ 18/06/2019 21:02:13 ] (400) Bad Request: chat not found
TelegramBot OnError ------------------

Does anyone know how to solve it?

**Comment by rareMaxim** [comment]
Вы пытаетесь отправить сообщение на неверно указанный Chat ID. Проверьте настройки демо.
