### ISSUE TITLE
После исключения в боте, ReceiverUI.IsActive возвращает True, но прием не работает

### ISSUE THREAD

**Issue by akella225** [ms301/CloudAPI#94]
При отправке, например, встроенной клавиатуры fBot.SendMessage() может возникнуть Exception, например, из-за того, что клавиатура некорректно создана или вовсе не создана. После исключения бот, вернее ресивер, останавливается и перестаёт реагировать на команды. При этом ReceiverUI.IsActive возвращает True.

**Comment by rareMaxim** [comment]
Нужен пример с багом. Увы, нет времени писать стенд
